Including exception regarding missing FONTBOUNDINGBOX parameter
adafruit/Adafruit_CircuitPython_Bitmap_Font pull request #43
Opened 2021-04-03 22:20 UTC by jposada202020

Including exception regarding missing FONTBOUNDINGBOX parameter in the font file.

Will produce
```python
Exception: Font does not have the FONTBOUNDINGBOX property. Try a different font
```

2021-04-03 22:25 UTC, jposada202020 commented
This was tested manually removing the FONTBOUNDINGBOX line in a bdf font file. Thanks!

2021-04-07 00:23 UTC, jepler requested changes
If a font can't `.get_bounding_box()`, are there other uses for it?

If not, why don't we handle this oddity in the constructor instead of here, by rejecting the font when it is first opened.

2021-04-07 01:03 UTC, jposada202020 commented
I do not think the font should be used. So answer will be no.

Just for reference: ``.get_bounding_box()`` is used in:

## bitmap_label
in the ``_line_spacing_ypixels`` function

## label
To define the height in ``self.height``


Not sure why there is this difference, but I agree with you to handle it in the constructor.  Thanks I will work on that and Re-submit

2021-04-07 17:22 UTC, jposada202020 commented
@jepler Chages were made. Two things:
A new attribute is created. This way it could be call in the future by the Text libraries (modification will be needed). However would works as you can see in the new  ``get_bounding_box()``
We still need to parse the first lines of code and get the value, so I create a new function not to put a lot of lines in the ``__init__ ``this is a design choice, but all the code could be done at ``__init__``. Just my preference, open to change if wanted.

2021-04-20 21:14 UTC, jposada202020 commented
Hey @jepler , this probably got lost in your inbox, but if you could review the requested changes when you get a chance, that would be great

2021-04-20 21:30 UTC, jepler approved these changes
Thanks!  Sorry I let this languish.

2021-04-20 21:30 UTC, merged

2021-04-20 21:34 UTC, jposada202020 commented
😃  Thanks